import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, stat, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const generatedPath = join(root, "apps", "api", "src", "generated", "resources.ts");

interface SourceResource {
  source: string;
  path: string;
  sha256: string;
  size: number;
}

async function filesUnder(directory: string): Promise<string[]> {
  const result: string[] = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) result.push(...(await filesUnder(path)));
    else if (entry.isFile()) result.push(path);
  }
  return result;
}

async function descriptor(source: string, path: string): Promise<SourceResource> {
  const bytes = await readFile(source);
  return {
    source,
    path: path.replaceAll("\\", "/"),
    sha256: createHash("sha256").update(bytes).digest("hex"),
    size: bytes.byteLength,
  };
}

const migrationsRoot = join(root, "apps", "api", "drizzle");
const tagsRoot = join(root, "packages", "tag-data", "data");
const webRoot = join(root, "apps", "web", "out");
if (!(await stat(join(webRoot, "index.html")).then((value) => value.isFile()).catch(() => false))) {
  throw new Error("Static web export is missing. Run the web build first.");
}

const extracted = [
  ...(await filesUnder(migrationsRoot)).map((source) => ({
    source,
    path: `migrations/${relative(migrationsRoot, source)}`,
  })),
  ...(await filesUnder(tagsRoot))
    .filter((source) => !source.endsWith("README.md"))
    .map((source) => ({ source, path: `tag-data/${relative(tagsRoot, source)}` })),
];
const staticFiles = (await filesUnder(webRoot)).map((source) => ({
  source,
  path: relative(webRoot, source),
}));
const extractedResources = await Promise.all(
  extracted.map(({ source, path }) => descriptor(source, path)),
);
const staticResources = await Promise.all(
  staticFiles.map(({ source, path }) => descriptor(source, path)),
);
function resourceSetHash(resources: readonly SourceResource[]): string {
  return createHash("sha256")
    .update(
      [...resources]
        .sort((left, right) => left.path.localeCompare(right.path))
        .map((item) => `${item.path}\0${item.sha256}\0${item.size}\n`)
        .join(""),
    )
    .digest("hex");
}
const contentHash = resourceSetHash(extractedResources);
const tagDataContentHash = resourceSetHash(
  extractedResources.filter((resource) =>
    resource.path.startsWith("tag-data/"),
  ),
);
const pkg = JSON.parse(await readFile(join(root, "package.json"), "utf8")) as {
  version: string;
};
const notices = await readFile(join(root, "THIRD_PARTY_NOTICES.md"), "utf8");
const all = [...extractedResources, ...staticResources];
const imports = all.map((item, index) => {
  const path = relative(dirname(generatedPath), item.source).replaceAll("\\", "/");
  return `import resource${index} from ${JSON.stringify(path.startsWith(".") ? path : `./${path}`)} with { type: "file" };`;
});
function render(items: SourceResource[], offset: number): string {
  return items
    .map(
      (item, index) =>
        `  { path: ${JSON.stringify(item.path.replaceAll("\\", "/"))}, sha256: "${item.sha256}", size: ${item.size}, blob: Bun.file(resource${offset + index}) },`,
    )
    .join("\n");
}
const source = `// @ts-nocheck -- generated asset imports are interpreted by Bun's file loader.\n// Generated by scripts/generate-portable-resources.ts. Do not edit.\nimport type { EmbeddedResource } from "../portable/resources";\n${imports.join("\n")}\n\nexport const APP_VERSION = ${JSON.stringify(pkg.version)};\nexport const RESOURCE_CONTENT_HASH = "${contentHash}";\nexport const TAG_DATA_CONTENT_HASH = "${tagDataContentHash}";\nexport const EXTRACTED_RESOURCES: readonly EmbeddedResource[] = [\n${render(extractedResources, 0)}\n];\nexport const STATIC_RESOURCES: readonly EmbeddedResource[] = [\n${render(staticResources, extractedResources.length)}\n];\nexport const THIRD_PARTY_NOTICES = ${JSON.stringify(notices)};\n`;
await mkdir(dirname(generatedPath), { recursive: true });
await writeFile(generatedPath, source, "utf8");
console.log(
  `Generated ${relative(root, generatedPath)} (${extractedResources.length} extracted, ${staticResources.length} static).`,
);
